// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA139u-GrEVz2DECvlTQSq049eU4jpjwPA',
    appId: '1:172313738627:web:c201a6283440d570788ab6',
    messagingSenderId: '172313738627',
    projectId: 'hotel-de-luna-5e60d',
    authDomain: 'hotel-de-luna-5e60d.firebaseapp.com',
    storageBucket: 'hotel-de-luna-5e60d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HcCNcdNn4pCYuMTAPQh4vbmVfkEVgJc',
    appId: '1:172313738627:ios:b540d94fec6c17b4788ab6',
    messagingSenderId: '172313738627',
    projectId: 'hotel-de-luna-5e60d',
    storageBucket: 'hotel-de-luna-5e60d.firebasestorage.app',
    iosBundleId: 'com.example.hotelDeLuna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_HcCNcdNn4pCYuMTAPQh4vbmVfkEVgJc',
    appId: '1:172313738627:ios:b540d94fec6c17b4788ab6',
    messagingSenderId: '172313738627',
    projectId: 'hotel-de-luna-5e60d',
    storageBucket: 'hotel-de-luna-5e60d.firebasestorage.app',
    iosBundleId: 'com.example.hotelDeLuna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA139u-GrEVz2DECvlTQSq049eU4jpjwPA',
    appId: '1:172313738627:web:73e6e39714f0eb22788ab6',
    messagingSenderId: '172313738627',
    projectId: 'hotel-de-luna-5e60d',
    authDomain: 'hotel-de-luna-5e60d.firebaseapp.com',
    storageBucket: 'hotel-de-luna-5e60d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNYBfRRJn1wLzvzI5-bH5EFGWlq_8eSs',
    appId: '1:172313738627:android:9e227a99bcf2b0b2788ab6',
    messagingSenderId: '172313738627',
    projectId: 'hotel-de-luna-5e60d',
    storageBucket: 'hotel-de-luna-5e60d.firebasestorage.app',
  );
}
